models:
- columns:
  - description: This is a unique identifier for a customer
    name: customer_id
    tests:
    - unique
    - not_null
  - description: Customer's first name. PII.
    name: first_name
  - description: Customer's last name. PII.
    name: last_name
  - description: Date (UTC) of a customer's first order
    name: first_order
  - description: Date (UTC) of a customer's most recent order
    name: most_recent_order
  - description: Count of the number of orders a customer has placed
    name: number_of_orders
  - description: Total value (AUD) of a customer's orders
    name: total_order_amount
  - description: Total lifetime value (GBP) of our customer
    name: customer_lifetime_value
  description: This table has basic information about a customer, as well as some
    derived facts based on a customer's orders
  name: customers
- columns:
  - description: This is a unique identifier for an order
    name: order_id
    tests:
    - unique
    - not_null
  - description: Foreign key to the customers table
    name: customer_id
    tests:
    - not_null
    - relationships:
        field: customer_id
        to: ref('customers')
  - description: Date (UTC) that the order was placed
    name: order_date
  - description: '{{ doc("orders_status") }}'
    name: status
    tests:
    - accepted_values:
        values:
        - placed
        - shipped
        - completed
        - return_pending
        - returned
  - description: Total amount (AUD) of the order
    name: amount
    tests:
    - not_null
  - description: Amount of the order (AUD) paid for by credit card
    name: credit_card_amount
    tests:
    - not_null
  - description: Amount of the order (AUD) paid for by coupon
    name: coupon_amount
    tests:
    - not_null
  - description: Amount of the order (AUD) paid for by bank transfer
    name: bank_transfer_amount
    tests:
    - not_null
  - description: Amount of the order (AUD) paid for by gift card
    name: gift_card_amount
    tests:
    - not_null
  description: This table has basic information about orders, as well as some derived
    facts based on payments
  name: orders
version: 2
